language: go
go_import_path: github.com/heptio/contour
go:
  - 1.12.x

sudo: false

cache:
  directories:
  - /home/travis/.cache/go-build
  - /home/travis/gopath/pkg/mod

env:
  - GOPROXY=https://proxy.golang.org/

script:
  - make check
