required = [
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
]

[[constraint]]
  name = "k8s.io/client-go"
  version = "v8.0.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.4"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.4"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.11.4"

[[constraint]]
  name = "github.com/envoyproxy/go-control-plane"
  # 0.6.1 matches Envoy v1.8.0, higher versions are for 1.9-dev
  version = "=0.6.1"
