apiVersion: v1
kind: Service
metadata:
 name: contour
 namespace: heptio-contour
 annotations:
   service.beta.kubernetes.io/aws-load-balancer-type: nlb
   # Scrape metrics for the contour container
   # The envoy container is scraped by annotations on the pod spec
   prometheus.io/port: "8000"
   prometheus.io/scrape: "true"
spec:
 ports:
 - port: 80
   name: http
   protocol: TCP
   targetPort: 8080
 - port: 443
   name: https
   protocol: TCP
   targetPort: 8443
 selector:
   app: contour
 type: LoadBalancer
---
